### ISSUE TITLE
booking record

### ISSUE THREAD

**Issue by yilinyang123** [dsi-principles-prog/midterm-yilinyang123#1]
The absence of date_first_booking means the destination is NDF(no destination found), thus we could add a column to indicate if there is a booking record. Then in prediction, we could eliminate the entries without booking record, and predicted the output, to be NDF(no destination found).

input: data frame, variable

output: 1(variable is not NA); 0(variable is NA)
Please write the function in chunk function3 in 30-feature-engineering
The expected outcome should look something like this when you call the function and select the variable and the new variable you generate
<img width="255" alt="截屏2019-10-27下午10 40 45" src="https://user-images.githubusercontent.com/54040073/67650400-d3ce1b80-f90a-11e9-9eef-b8c79554f161.png">
Please call the function and add the new variable in prepared data in chunk prepare data in 40-modelling
Please test with asserts/verifys on the new feature to ensure its values only contain 0 and 1.
Please write the asserts/verifys function in chunk test function3 in 40-modelling

**Comment by volcano1998** [comment]
Yilin's statement is very clear and I've finished this function with no question.
